#!/bin/bash
# Quick commands for GA4 Performance Tracker

echo "🎯 GA4 Performance Tracker - Quick Commands"
echo "============================================"
echo ""
echo "Test GA4 Setup:"
echo "  python3 scripts/test_ga_tracker.py"
echo ""
echo "View Dashboard (last 7 days):"
echo "  python3 scripts/view_ga_dashboard.py"
echo ""
echo "View Dashboard (last 30 days):"
echo "  python3 scripts/view_ga_dashboard.py --days 30"
echo ""
echo "Export Report:"
echo "  python3 scripts/view_ga_dashboard.py --export"
echo ""
echo "Test Import:"
echo "  python3 -c 'from src.dashboard.performance_tracker import GA4PerformanceTracker; print(\"✅ OK\")'"
echo ""
echo "Quick Metrics:"
echo "  python3 -c 'from src.dashboard.performance_tracker import GA4PerformanceTracker; t=GA4PerformanceTracker(); m=t.get_website_metrics(7); print(f\"Users: {m[\"users\"]}, Sessions: {m[\"sessions\"]}\")'"
echo ""
echo "============================================"
